// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransporteApp.Data;

#nullable disable

namespace TransporteApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransporteApp.Models.Automovil", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Conductor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Automoviles");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Conductor = "Diana"
                        },
                        new
                        {
                            Id = 4,
                            Conductor = "Sofía"
                        },
                        new
                        {
                            Id = 6,
                            Conductor = "Roberto"
                        });
                });

            modelBuilder.Entity("TransporteApp.Models.Avion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Copiloto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Piloto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Aviones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Copiloto = "Pedro",
                            Piloto = "Luis"
                        },
                        new
                        {
                            Id = 3,
                            Copiloto = "Marco",
                            Piloto = "Carlos"
                        },
                        new
                        {
                            Id = 5,
                            Copiloto = "Jorge",
                            Piloto = "Andrea"
                        });
                });

            modelBuilder.Entity("TransporteApp.Models.Transporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Ancho")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Largo")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("NumeroPasajeros")
                        .HasColumnType("int");

                    b.Property<int>("NumeroRuedas")
                        .HasColumnType("int");

                    b.Property<int>("Secuencia")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Transportes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ancho = 5.4m,
                            Color = "Blanco",
                            Largo = 32.5m,
                            NumeroPasajeros = 180,
                            NumeroRuedas = 6,
                            Secuencia = 3,
                            Tipo = "Avion"
                        },
                        new
                        {
                            Id = 2,
                            Ancho = 1.8m,
                            Color = "Rojo",
                            Largo = 4.2m,
                            NumeroPasajeros = 5,
                            NumeroRuedas = 4,
                            Secuencia = 1,
                            Tipo = "Automovil"
                        },
                        new
                        {
                            Id = 3,
                            Ancho = 6.1m,
                            Color = "Azul",
                            Largo = 40.0m,
                            NumeroPasajeros = 200,
                            NumeroRuedas = 8,
                            Secuencia = 6,
                            Tipo = "Avion"
                        },
                        new
                        {
                            Id = 4,
                            Ancho = 1.75m,
                            Color = "Negro",
                            Largo = 4.0m,
                            NumeroPasajeros = 4,
                            NumeroRuedas = 4,
                            Secuencia = 2,
                            Tipo = "Automovil"
                        },
                        new
                        {
                            Id = 5,
                            Ancho = 5.8m,
                            Color = "Gris",
                            Largo = 35.3m,
                            NumeroPasajeros = 150,
                            NumeroRuedas = 10,
                            Secuencia = 5,
                            Tipo = "Avion"
                        },
                        new
                        {
                            Id = 6,
                            Ancho = 1.9m,
                            Color = "Verde",
                            Largo = 4.5m,
                            NumeroPasajeros = 5,
                            NumeroRuedas = 4,
                            Secuencia = 4,
                            Tipo = "Automovil"
                        });
                });

            modelBuilder.Entity("TransporteApp.Models.Automovil", b =>
                {
                    b.HasOne("TransporteApp.Models.Transporte", "Transporte")
                        .WithOne("Automovil")
                        .HasForeignKey("TransporteApp.Models.Automovil", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transporte");
                });

            modelBuilder.Entity("TransporteApp.Models.Avion", b =>
                {
                    b.HasOne("TransporteApp.Models.Transporte", "Transporte")
                        .WithOne("Avion")
                        .HasForeignKey("TransporteApp.Models.Avion", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transporte");
                });

            modelBuilder.Entity("TransporteApp.Models.Transporte", b =>
                {
                    b.Navigation("Automovil");

                    b.Navigation("Avion");
                });
#pragma warning restore 612, 618
        }
    }
}
